### ISSUE TITLE
column total as a row

### ISSUE THREAD

**Issue by Edimo05** [chelmerrox/react-data-table-tutorial#1]
Is it possible to add a final row with the total of a specific column?
Let's say I want to have the total for column Cost on the image.

![image](https://github.com/user-attachments/assets/0574904f-6781-43ba-96aa-d5484da9927b)

**Comment by chelmerrox** [comment]
Hi @Edimo05, 👋🏽🙂

The library doesn't provide a feature/prop to have a fixed footer at the bottom, such as for displaying the total for "Costo". It only has a prop for a fixed header (`fixedHeader`).

To do that, it'll need more customizations.

You can refer to the [documentation](https://react-data-table-component.netlify.app/?path=/docs/getting-started-intro--docs) for more info.
